---
title: "PolicyProject"
output: html_document
date: "2023-09-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This project will explore the relationship between the increasing price of energy and its effect on the UK's transport services.

```{r, warning = FALSE, message = FALSE}
library("tidyverse")
library("ggplot2")
library("readxl")
library("openxlsx")

```

# first explore



```{r, }
excel_file <- "Data/householdfinances9to20august2023final.xlsx"
col_list <- c("Dates", "All_perc", "LCL", "UCL")
data <- read_excel(excel_file, sheet = "7")

data <- data[9:nrow(data),]
colnames(data)<- col_list
data<- data[-1,]

data$All_perc <- as.numeric(data$All_perc)
data$Dates <- factor(data$Dates, levels = data$Dates)

head(data)

```


```{r, }
ggplot(data, aes(x = Dates, y = All_perc)) +
  geom_point() +
  geom_smooth(method = "lm") +
  coord_flip()
  
```


# chaps

```{r}
excel_file <- "Data/ukspendingoncreditanddebitcardsdataset010923.xlsx"

data <- read_excel(excel_file, sheet = "Daily CHAPS indices")

data <- data[3:nrow(data),]

colnames(data)<- data[1,]
data<- data[-1,]
data$Date <- convertToDateTime(data$Date)

numeric_columns <- c("Aggregate", "Delayable", "Social", "Staple", "Work Related")  # Replace with your column names
data[numeric_columns] <- lapply(data[numeric_columns], as.numeric)

data = pivot_longer(data, cols = numeric_columns, names_to = "Type")
head(data)
```
```{r}
retail_data <- read.csv("Data/retail-price-comparison.csv")
retail_names <- c("Date", "Avg_st_large", "Avg_st_other", "Avg_fixed", "Cheap_tarr_large", "Cheap_tarr_all_supp", "Cheap_tarr_bask", "Default")
colnames(retail_data) <- retail_names
retail_data$Date <- format(as.POSIXct(retail_data$Date,format='%Y-%m-%d %H:%M:%S'),format='%Y-%m-%d')
retail_data$Date<- as.POSIXct(retail_data$Date, format="%Y-%m-%d", tz="UTC")
head(retail_data)
```
```{r}
ggplot(retail_data, aes(x = Date,y = Avg_st_large)) +
  geom_line()
```

```{r}
ggplot(data, aes(x = Date, y = value)) +
  geom_line() +
  facet_wrap(~Type)
```

